Start circular animation from previous value
OpenLitterMap/react-native pull request #87
Opened 2021-09-06 14:13 UTC by sudoDeznit

2021-09-09 22:32 UTC, xlcrr reviewed
Need to test this

2021-09-09 22:32 UTC, xlcrr commented on screens/components/AnimatedCircle.js
> +            duration: duration,
1 var is enough

2021-09-10 20:47 UTC, xlcrr commented
Error on UserStats screen

```
This error is located at:
    in AnimatedCircle (at ProgressCircleCard.js:24)

Error: AnimatedValue: Attempting to set value to undefined
```

![simulator_screenshot_41B23A91-7685-42CB-8D04-230083A6D0BA](https://user-images.githubusercontent.com/25985241/132915708-62db8443-3b48-4472-b8a5-8d2c34f35b2b.png)

```
[Fri Sep 10 2021 21:45:52.325]  WARN     Sending `onAnimatedValueUpdate` with no listeners registered.
[Fri Sep 10 2021 21:45:54.337]  WARN     Possible Unhandled Promise Rejection (id: 0):
Error: AnimatedValue: Attempting to set value to undefined
```

2021-09-10 20:47 UTC, xlcrr requested changes
bug found

2021-09-14 21:44 UTC, xlcrr commented
@sudoDeznit I got a bug on this PR, can you try to duplicate it?

2021-09-16 14:08 UTC, sudoDeznit commented
Not able to reproduce the error. Tried old account and also new account with 0 images uploaded.
Were you trying on staging or prod ??

2021-09-16 20:55 UTC, xlcrr commented
Does not work. App crashes when you change screen while animation is occuring

2021-09-16 20:55 UTC, xlcrr commented
![simulator_screenshot_5C6E648C-22CB-4C3A-9C84-E1F598575BCE](https://user-images.githubusercontent.com/25985241/133684389-f71dd276-d7ad-47ea-b9dd-d438465cfd2a.png)

2021-09-16 21:27 UTC, xlcrr requested changes
Breaks when changing screen while progress animation is happening

2021-10-21 17:14 UTC, closed without merging